

CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

FRAME_RATE = 30

FORMAT = "BGR888"


RESOLUTION = (CAMERA_WIDTH, CAMERA_HEIGHT)
SHOW_PREVIEW = True #set false when running headless

#FALLBACK IMAGE FOR DEV
DEV_IMAGE_PATH = "test/fallback/6.jpg"