



#GPIO PINS
BUTTON_TRIGGER_PIN = 23

LED_SIGNAL_PIN = 13

REBOOT_TRIGGER_PIN = 21
SHUTDOWN_TRIGGER_PIN = 24

BUTTON_BOUNCE_TIME = 1000
SHUTDOWN_BUTTON_BOUNCE_TIME = 500

#HOLD BUTTON TIMINGS
SHUTDOWN_HOLD_DURATION = 2
HOLD_POLL_INTERVAL = 0.005 #hold often to recheck during the hold

TRIGGER_CONFIRM_DURATION = 0.15

#LED RELATED
LED_COUNT = 5
BRIGHTNESS = 80

#ESP RELATED
SERIAL_PORT = '/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0'
BAUD_RATE = 115200