





GACHA_WINDOW_START = 11 # hour
GACHA_WINDOW_END = 19 # hour

GACHA_PEAK_START = 13
GACHA_PEAK_END = 17

GACHA_BASE_PROBABLITY = 1.0 #TESTING
GACHA_PEAK_PROBABILITY = 0.065
GACHA_RAMP_RATE = 0.03

GACHA_GUARANTEED_HOUR = 18

#FX

CHROMATIC_ABBERATION_OFFSET_MIN = 4
CHROMATIC_ABBERATION_OFFSET_MAX = 12


SCANLINES_SPACING_MIN = 6
SCANLINES_SPACING_MAX = 10

SCANLINES_OPACITY_MIN = 20
SCANLINES_OPACITY_MAX = 45


VIGNETTE_MULTI = 80

GHOST_PRINT_ORIGINAL_WEIGHT = 0.6 #how much original shows through
GHOST_PRINT_GHOST_WEIGHT = 0.25 #how much original shows through


GLITCH_SHIFT_BANDS_MIN = 5 #NUMBER OF GLITCH BANDS
GLITCH_SHIFT_BANDS_MAX = 15
GLITCH_SHIFT_AMOUNT_MIN = 30 # PIXELS TO SHIFT
GLITCH_SHIFT_AMOUNT_MAX = 120 #PIXELS TO SHIFT
GLITCH_BAND_HEIGHT_MIN = 5 #HEIGHT OF GLITCH BANDS
GLITCH_BAND_HEIGHT_MAX = 40 #HEIGHT OF GLITCH BANDS
