





GACHA_WINDOW_START = 10 # hour
GACHA_WINDOW_END = 19 # hour

GACHA_PEAK_START = 13
GACHA_PEAK_END = 17

GACHA_BASE_PROBABLITY = 0.03 #TESTING
GACHA_PEAK_PROBABILITY = 0.065
GACHA_RAMP_RATE = 0.026

GACHA_GUARANTEED_HOUR = 18

#FX

CHROMATIC_ABBERATION_OFFSET_MIN = 15
CHROMATIC_ABBERATION_OFFSET_MAX = 40


SCANLINES_SPACING_MIN = 3
SCANLINES_SPACING_MAX = 6

SCANLINES_OPACITY_MIN = 40
SCANLINES_OPACITY_MAX = 70


VIGNETTE_MULTI = 80

GHOST_PRINT_ORIGINAL_WEIGHT = 0.55 #how much original shows through
GHOST_PRINT_GHOST_WEIGHT = 0.38 #how much original shows through


GLITCH_SHIFT_BANDS_MIN = 5 #NUMBER OF GLITCH BANDS
GLITCH_SHIFT_BANDS_MAX = 15
GLITCH_SHIFT_AMOUNT_MIN = 30 # PIXELS TO SHIFT
GLITCH_SHIFT_AMOUNT_MAX = 120 #PIXELS TO SHIFT
GLITCH_BAND_HEIGHT_MIN = 5 #HEIGHT OF GLITCH BANDS
GLITCH_BAND_HEIGHT_MAX = 40 #HEIGHT OF GLITCH BANDS

NOISE_INTENSITY = 40

BLOCK_CORRUPT_MIN = 3
BLOCK_CORRUPT_MAX = 10
BLOCK_SIZE_MIN = 20
BLOCK_SIZE_MAX = 80

INVERT_BANDS_MIN = 2
INVERT_BANDS_MAX = 6
INVERT_BAND_HEIGHT_MIN = 10
INVERT_BAND_HEIGHT_MAX = 40