





GACHA_WINDOW_START = 11 # hour
GACHA_WINDOW_END = 19 # hour

GACHA_PEAK_START = 13
GACHA_PEAK_END = 17

GACHA_BASE_PROBABLITY = 0.03
GACHA_PEAK_PROBABILITY = 0.065
GACHA_RAMP_RATE = 0.03

GACHA_GUARANTEED_HOUR = 18

#FX

CHROMATIC_ABBERATION_OFFSET_MIN = 8
CHROMATIC_ABBERATION_OFFSET_MAX = 20


SCANLINES_SPACING_MIN = 4
SCANLINES_SPACING_MAX = 8

SCANLINES_OPACITY_MIN = 40
SCANLINES_OPACITY_MAX = 80