

#REGION BOUNDARIES


TOP_REGION_END = 1/3 #top third

MIDDLE_REGION_START = 1/3 
MIDDLE_REGION_END = 2/3

BOTTOM_REGION_START = 2/3


#HUE SATURATION VALUES THRESHOLDS
HUE_WARM_MAX = 35 # 0 - 35 is warm
HUE_COOL_MIN = 85 # 85 - 130 is cool
HUE_COOL_MAX = 130 

#SATURATION VALUES
SAT_NEUTRAL_MAX = 50
SAT_MIN_THRESHOLD = 50


#VALUE THRESHOLDS
VALUE_DARK_MAX = 85  #below = dark
VALUE_LIGHT_MIN = 170 # above = light

#CAMERA SETTINGS
CAMERA_RESOLUTION = ( 1920 , 1080)
CAMERA_INDEX = 0