
import platform
import os

#REGION BOUNDARIES
DEV_MODE = platform.system() != "Linux" 

#STATUS SERVER
STATUS_SERVER_PORT = 8080

#TO CONNECT TO CAMERAPI
CAMERA_PI_IP = "192.168.2.2"
CAMERA_PI_PORT = 5000
CAMERA_HEALTH_CHECK_INTERVAL = 10 #(seconds between pings)
SHOW_DETECTIONS = DEV_MODE
CAMERA_STREAM_RECONNECTION_INTERVAL = 5

#OUTPUT DIRECTORY
OUTPUTS_DIR = "outputs"
SELPHY_OUTPUTS_DIR = "outputs/selphy"
THERMAL_OUTPUTS_DIR = "outputs/thermal"

#FALLBACK DIRECTORY
FALLBACK_IMAGE_PATH = "test/fallback/fallback_3.png"

#INSTALLATION NAMES
SELPHY_PRINTER_NAME = "Selphy"
THERMAL_VENDOR_ID = 0x1fc9
THERMAL_PRODUCT_ID = 0x2016
#PATH FOR THERMAL PRINTER
THERMAL_DEVICE_PATH = "/dev/usb/lp0"

SELPHY_PRINT_COOLDOWN = 100 #90s print + 10s buffer
THERMAL_PRINT_COOLDOWN = 10 #5s print + 5s Buffer
TRIGGER_DEBOUNCE_SECONDS = 30
PRINT_ERROR_COOLDOWN = 60

SKIP_PRINT = True

#REGIONS
TOP_REGION_END = 1/3 #top third

MIDDLE_REGION_START = 1/3 
MIDDLE_REGION_END = 2/3

BOTTOM_REGION_START = 2/3









