
import platform
import os

#REGION BOUNDARIES
DEV_MODE = platform.system() != "Linux" 
STRESS_TEST = False
STRESS_TEST_INTERVALS =240
STRESS_TEST_MAX_TRIGGERS = 240

#STATUS SERVER
STATUS_SERVER_PORT = 8080

#TO CONNECT TO CAMERAPI
CAMERA_PI_IP = "192.168.2.2"
CAMERA_PI_PORT = 5000
CAMERA_HEALTH_CHECK_INTERVAL = 10 #(seconds between pings)
SHOW_DETECTIONS = DEV_MODE
CAMERA_STREAM_RECONNECTION_INTERVAL = 5

#OUTPUT DIRECTORY
OUTPUTS_DIR = "outputs"
SELPHY_OUTPUTS_DIR = "outputs/selphy"
THERMAL_OUTPUTS_DIR = "outputs/thermal"

#FALLBACK DIRECTORY
FALLBACK_IMAGE_PATH = "test/fallback/fallback_6.jpg"

#INSTALLATION NAMES
SELPHY_PRINTER_NAME = "Selphy"
THERMAL_VENDOR_ID = 0x1fc9
THERMAL_PRODUCT_ID = 0x2016
#PATH FOR THERMAL PRINTER
THERMAL_DEVICE_PATH = "/dev/usb/lp0"

SELPHY_PRINT_COOLDOWN = 50 #60s print + 10s buffer
THERMAL_PRINT_COOLDOWN = 10 #5s print + 5s Buffer

TRIGGER_DEBOUNCE_SECONDS = 15
PRINT_ERROR_COOLDOWN = 60

TRIGGER_HOLD_SECONDS = 0.5
COMPLETED_HOLD_SECONDS = 1.5 

SKIP_PRINT = False

#CAUTIOUS STATE FIRING
INK_RIBBON_MAX_CAPACITY = 54
PAPER_PACK_MAX_CAPACITY = 18
PAPER_CAUTION_REMAINING = 3 # WARN WHEN THERES 3 SHEETS LEFT
INK_RIBBON_CAUTION_REMAINING = 5 # WARN WITH 5 PRINTS LEFT
CONSUMABLES_STATE_PATH = "consumable_state.json"



#REGIONS
TOP_REGION_END = 1/3 #top third

MIDDLE_REGION_START = 1/3 
MIDDLE_REGION_END = 2/3

BOTTOM_REGION_START = 2/3









