
import platform
import os

#REGION BOUNDARIES
DEV_MODE = platform.system() != "Linux" 
#DEV_MODE = True

#OUTPUT DIRECTORY
OUTPUTS_DIR = "outputs"
SELPHY_OUTPUTS_DIR = "outputs/selphy"
THERMAL_OUTPUTS_DIR = "outputs/thermal"

#FALLBACK DIRECTORY
FALLBACK_IMAGE_PATH = "test/fallback/fallback_3.png"

#INSTALLATION NAMES
SELPHY_PRINTER_NAME = "Selphy"
THERMAL_VENDOR_ID = None
THERMAL_PRODUCT_ID = None

#REGIONS
TOP_REGION_END = 1/3 #top third

MIDDLE_REGION_START = 1/3 
MIDDLE_REGION_END = 2/3

BOTTOM_REGION_START = 2/3









