interface=wlan0 #only hand out IPS on the wifi interface , not ethernet

no-hosts #dont use the pi's etc/hosts file for DNS

dhcp-range=192.168.50.10, 192.168.50.50,255.255.255.0,24h #when device connects , give it IP between .10 and .50 , valid for 24 hours