interface=wlan0 #uses wifi chip
driver=n180211 #standard linux WIFI driver
ssid=supervision_iaf #networkname to find on phone
hw_mode=g #2.4ghz wifi
channel=7 #which wifi channel to broadcast
wpa=2 #wpa2 security
wpa_passphrase=supervision #wifi password
wph_key_mgmt=WPA-PSK #password based authentication
rsn_pairwise=CCP #encryption standard